USE database_name;

CREATE TABLE AB_MESSAGE (
    ID INT AUTO_INCREMENT,
        CONSTRAINT AB_MESSAGE_ID PRIMARY KEY (ID),
    USER_FROM INT,
        CONSTRAINT USER_FROM_FK FOREIGN KEY (USER_FROM) REFERENCES AA_USER(ID),
    USER_TO INT,
        CONSTRAINT USER_TO_FK FOREIGN KEY (USER_TO) REFERENCES AA_USER(ID),
    TEXTS VARCHAR(140),
    DATE_SENT DATE,
    DATE_EDITED DATE,
    DATE_READ DATE,
    DATE_DELETED DATE,
    CONDITION_MESSAGE BOOLEAN
);