USE database_name;

CREATE TABLE AC_POST (
    ID INT AUTO_INCREMENT,
        CONSTRAINT AC_POST_ID PRIMARY KEY (ID),
    USER_POSTED INT,
        CONSTRAINT USER_POSTED_FK FOREIGN KEY (USER_POSTED) REFERENCES AA_USER(ID),
    USER_PAGE_POSTED INT,
        CONSTRAINT USER_PAGE_POSTED_FK FOREIGN KEY (USER_PAGE_POSTED) REFERENCES AA_USER(ID),
    MESSAGE VARCHAR(200),
    DATA_POSTED DATE,
    LOCATION VARCHAR(200)
);
