USE database_name;

CREATE TABLE AB_MESSAGE (
    ID INT AUTO_INCREMENT,
        CONSTRAINT AB_MESSAGE_ID PRIMARY KEY (ID),
    TEXT LONGTEXT,
    DATE_SENT DATE,
    DATE_READ DATE,
    USER_FROM INT,
        CONSTRAINT USER_FROM_FK FOREIGN KEY (USER_FROM) REFERENCES AA_USER(ID),
    USER_TO INT,
        CONSTRAINT USER_TO_FK FOREIGN KEY (USER_TO) REFERENCES AA_USER(ID)
);

