USE database_name;

CREATE TABLE AD_RELATIONSHIP (
    ID INT AUTO_INCREMENT,
        CONSTRAINT AD_RELATIONSHIP_ID PRIMARY KEY (ID),
    USER_FROM_ID VARCHAR(50),
    USER_TO_ID VARCHAR(50),
    STATUS ENUM ('NOT_FRIENDS','REQUEST','REQUEST_DENIED','FORMER_FRIENDS','FRIENDS')
);


SELECT * FROM AD_RELATIONSHIP;
#  поиск друзей
SELECT * FROM AD_RELATIONSHIP WHERE USER_FROM_ID = ? AND STATUS = 'FRIENDS';
#  поиск кто мне оптравил запрос
SELECT * FROM AD_RELATIONSHIP WHERE USER_TO_ID = ? AND STATUS = 'REQUEST';
#  поиск кому я отправил запрос
SELECT * FROM AD_RELATIONSHIP WHERE USER_FROM_ID = ? AND STATUS = 'REQUEST'

#  добавление заявки
SELECT * FROM AD_RELATIONSHIP
WHERE (USER_FROM_ID = ? AND USER_TO_ID = ?  AND STATUS = 'REQUEST') OR (USER_TO_ID = ? AND USER_FROM_ID = ? AND STATUS = 'REQUEST');