USE database_name;

CREATE TABLE AE_USER_POST(
    USER_ID INT,
        CONSTRAINT USER_ID_FK FOREIGN KEY (USER_ID) REFERENCES AA_USER(ID),
    POST_ID INT,
        CONSTRAINT POST_ID_FK FOREIGN KEY (POST_ID) REFERENCES AC_POST(ID)
);